### PR TITLE
Extension namespace fix to be PSR-4 compatible after monorepo merge

### LINKED ISSUE #18: Configuration of Behat and PhpSpec extensions
The class definitions for `behat.yml` and `phpspec.yml` in the Configuration section of `README.md` both result in class not found errors running behat and phpspec.

I believe instead of:
  `RMiller\BehatSpec\BehatExtension` and `RMiller\BehatSpec\PhpSpecExtension` 
they should be:
  `RMiller\BehatSpecExtension\BehatExtension` and `RMiller\BehatSpecExtension\PhpSpecExtension`

### PR DESCRIPTION
**Pull request by ek9**
This is a big PR with the following changes:
- The namespaces have been updated to be compatible with PSR-4 and reflect the updated structure after everything has been moved to monorepo. This mostly means that everything is under `RMiller\BehatSpec` now (`src/`), thus `src/Extension` becomes `RMiller\BehatSpec\Extension`. This was a bigger change, but I have updated all the related composer.json files + tests + retested everything to make sure all of the extensions work fine.
- PHPSpec related extension requirements updated PHP requirement from 5.4+ to 5.6+ (phpspec3 requires 5.6+)
- Update `composer.json` of `behat-spec` package to efficiently and correctly load extension via `PSR-4`
- Updated README.md to ask using `v0.3.*` for PHPSpec2 support until `v0.4.*` is stable.
- Updated README.md in main and all extensions to use the new namespaces

This is related to and fixes #18 #23 

I have made sure all the tests pass in all extensions where the tests were setup. There is still ExemplifyExtension tests failing, but it's same failures that were there before this PR (I've made a sparate issue to track it)

### CODE REVIEW

**Comment by ek9** [comment]
I belive `src/Extension` directory is setup as part of subtreesplit. I would suggest to get rid of that instead and use `src/<EXTENSION>` structure. We could then also remove the `Extension` sub-namespace to clean it up, however that would require further updates to subtreesplit + break compatibility with `0.4`

**Comment by ek9** [comment]
This would fix #25

**Comment by ek9** [comment]
This would also fix #5 as I have tried running the updated version on an existing behat/phpspec heavy project which previously relied on phpspec2 and it seems to work fine with PHPSpec3 so far.

**Comment by richardmiller** [comment]
Brilliant, thank you for this!

**Pull request merged**
